# Config files for snakemake workflow
# Configs make sharing pipelines easier because the new person only really needs to change this config file so accidental changes to the logic of the pipeline can't happen as easily etc.
